<div id="sidebar">
<ul>
<li><a href="http://helios.ite.gmu.edu/~ghuang3/IT%20207/index.shtml">Home Page</a></li>
</ul>
<strong>Lab Assignments</strong>
<ul>
<li><a href="http://helios.ite.gmu.edu/~ghuang3/IT%20207/Lab%20Assignment%201/assignment1.php">Assignment 1</a></li>
<li><a href="http://helios.ite.gmu.edu/~ghuang3/IT%20207/Lab%20Assignment%202/assignment2.php">Assignment 2</a></li>
<li><a href="http://helios.ite.gmu.edu/~ghuang3/IT%20207/Lab%20Assignment%203/assignment3.php">Assignment 3</a></li>
<li><a href="http://helios.ite.gmu.edu/~ghuang3/IT%20207/Lab%20Assignment%204/assignment4.php">Assignment 4</a></li>
</ul>
<strong>Lab Practica</strong>
<ul>
<li><a href="http://helios.ite.gmu.edu/~ghuang3/IT%20207/Practicum%201/part1.html">Practicum 1</a></li>
<li><a href="http://helios.ite.gmu.edu/~ghuang3/IT%20207/Practicum%202/practicum%202.php">Practicum 2</a></li>
</ul>
</div>